name: Mirror government AQI data

on:
  push:
  schedule:
    - cron: "30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save new json
        run: bash update
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: "data/*.json"
